### ISSUE TITLE
EBS_OPTIMIZED at boot

### ISSUE THREAD

**Issue by ujjwal** [cloudera/director-aws-plugin#2]
Hello.

Trying to figure out how to specify if a EBS mounted volume should be set EBS_OPTIMIZED?

**Comment by andreisavu** [comment]
For many new instance types this is on by default:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html 

What are you using? Is this the root disk device or a different drive?

**Comment by ujjwal** [comment]
Thanks. Yeah that flag is confusing on the EC2 side.
