### ISSUE TITLE
Director 2.5 doesn't allow Name tags

### ISSUE THREAD

**Issue by vinceprignano** [cloudera/director-aws-plugin#3]
When the instance template specifies a Name tag, Director 2.5 appends without checking if the name was already specified.

```do│[2017-07-15 21:07:57.520 +0000] ERROR [p-ba78a1cebaab-AllocateInstances] 21e43190-b491-4f20-9db6-5750ff1bbed3 PUT /api/v9/environments/ausw1a/deployments/ausw1a-cm5_10_1/clusters/lender-ausw1a com.cl│
* │oudera.launchpad.bootstrap.AllocateInstances$AllocateAndWaitForInstancesToRun - c.c.director.aws.ec2.EC2Provider: Exception while trying to allocate instance.                                         │
* │java.util.concurrent.ExecutionException: com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.model.AmazonEC2Exception: Duplicate tag key 'Name' specified. (Service: AmazonEC2; Status Code: 40│..
..│0; Error Code: InvalidParameterValue; Request ID: cde4ca05-8ddc-4b79-92f8-11cc50850d37)                                                                                                         	  │
* │Caused by: com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.model.AmazonEC2Exception: Duplicate tag key 'Name' specified. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParamete│
* │rValue; Request ID: cde4ca05-8ddc-4b79-92f8-11cc50850d37)
```

Related code https://github.com/cloudera/director-aws-plugin/blob/8f21c1623d5675178024ba7124bb719bb560f057/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java#L120-L122

**Comment by meowfaceman** [comment]
Letting you know we're aware of this bug and are working it internally. We've utilized AWS's new tag-on-create feature for on-demand instances, but it seems that this is less permissive about duplicate tags than our previous mechanism. Previously it seems that user supplied tags would win out vs. the AWS plugin's internal name tag, but the new command errors out.

We did predict that this could be an issue, and thus the AWS plugin has a mechanism to allow renaming of our internal tags using CustomTagMappings. However, looks like we've got a bug in our CustomTagMappings code (stemming from the same class) which renames user supplied tags as well, so it's not currently available as a fix. I'll let you know when we've fixed this!

**Comment by vinceprignano** [comment]
Thanks!

**Comment by meowfaceman** [comment]
Hi @vinceprignano, this has been corrected with the release of Director 2.5.1. CustomTagMappings has been corrected in 2.5.1, so you should be able to work around this now: http://docs.mtv.cloudera.com/builds/docs-director-master-d4p/latest/topics/director_aws_custom_tag_names.html

Please give that a try and let me know if that works for you. If so I'll close the issue. Thanks!

**Comment by sdavids13** [comment]
> We've utilized AWS's new tag-on-create feature for on-demand instances, but it seems that this is less permissive about duplicate tags than our previous mechanism.

The tag-on-create feature isn't available in all regions, did the fix happen to take that into account and perhaps revert back to the old way?

**Comment by meowfaceman** [comment]
@sdavids13 Unfortunately those regions -- AWS China and GovCloud, at least according to [this](https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/) -- are not currently supported by Director 2.5 (see the KI [here](https://www.cloudera.com/documentation/director/latest/topics/director_rn_known_issues.html#concept_ppy_v4s_w1b)). Director 2.4.1 should still work just as well, and additionally will not have this particular issue as described, e.g. you can supply your own Name tags.

You could potentially compile the [older version of the plugin](https://github.com/cloudera/director-aws-plugin/releases/tag/cloudera-director-2.4.1) to 2.5.1 if you want to take advantage of new features in Director 2.5.1 as well, though this isn't something that we test for.

**Comment by vinceprignano** [comment]
@meowfaceman It seems that the issue still remains though. Our template specifies a custom name like
```config
tags {
    Name: "zookeeper"${?suffix}
    environment: "production"
}
```

It seems that the current plugin doesn't check if the Name tag is already specified, therefore it may cause issues with duplicate values.

**Comment by meowfaceman** [comment]
@vinceprignano This is after configuring the AWS plugin for customTagMappings as per http://docs.mtv.cloudera.com/builds/docs-director-master-d4p/latest/topics/director_aws_custom_tag_names.html? You should be able to tell Director not to use the Name field to make room for the custom Name field that you want to provide.

**Comment by vinceprignano** [comment]
I don't have access to that link. Is the public one this https://www.cloudera.com/documentation/director/latest/topics/director_aws_custom_tag_names.html? I'm not sure how to tell Director not to use the Name field from those docs.

**Comment by meowfaceman** [comment]
Oops, thank you, my bad. That's the correct link. When you install Director, there should be a /var/lib/cloudera-director-plugins/aws-provider-1.4.3/etc/aws-plugin.conf. If you add in a customTagMappings blurb to that file as specified in teh docs, it will rename what tag Director uses. So, for example:

```
customTagMappings {
    Name: some-other-tag
}
```

Instead of using the Name tag, it will use some-other-tag instead, allowing you to use the Name tag.

**Comment by vinceprignano** [comment]
Oh I see! Thanks :)

**Comment by vinceprignano** [comment]
@meowfaceman I just tried to apply the proposed fix. Although that didn't work as expected. It seem that even if I rename the Name tag, Director uses the same Key as tag. This seems to be happening here https://github.com/cloudera/director-aws-plugin/blob/master/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java#L120-L122 where the call to https://github.com/cloudera/director-aws-plugin/blob/master/provider/src/main/java/com/cloudera/director/aws/Tags.java#L53 returns still `Name`

**Comment by handavid** [comment]
@vinceprignano The code replaces the "Name" with the CustomTagMapping in the createTag method. see https://github.com/cloudera/director-aws-plugin/blob/master/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java#L76

Can you verify that you are using the aws plugin version 1.4.3, shipped with Cloudera Director 2.5.1?
Can you share your aws-plugin.conf file?

**Comment by vinceprignano** [comment]
The version seems correct. 

```bash
[ec2-user@ip-XXX5 ~]$ cat /var/lib/cloudera-director-plugins/aws-provider-1.4.3/etc/aws-plugin.conf
customTagMappings {
    Name: Director-Name
}
awsFilters {
    "com.cloudera.director.aws.ec2.EC2Provider" {
        template {
            image {
                ownerId {
                    blacklist {
                        "137112412989": "Amazon Linux",
                        "379101102735": Debian,
                        "125523088429": Fedora,
                        "902460189751": "Dowd and Associates Pygoscelis-Papua, Gentoo",
                        "341857463381": Gentoo,
                        "056126556840": "SUSE Studio, OpenSUSE",
                        "013907871322": "Amazon, SUSE Linux",
                        "099720109477": "Canonical, Ubuntu"
                    }
                },
                platform {
                    blacklist {
                        "amazon linux": "Amazon Linux",
                        debian: Debian,
                        fedora: Fedora,
                        gentoo: Gentoo,
                        opensuse: OpenSUSE,
                        "suse linux": "SUSE Linux",
                        ubuntu: Ubuntu,
                        windows: Windows
                    }
                },
                spotOwnerId {
                    blacklist {
                        "309956199498": RedHat
                    }
                },
                spotPlatform {
                    blacklist {
                        "red hat": "Red Hat"
                    }
                }
            }
        }
    }
}
```

This is the patch I applied after the same error happened.

```patch
From 1c10839437b66aafd76d28693632371d75bf8c46 Mon Sep 17 00:00:00 2001
From: Vincenzo Prignano <vincenzo.prignano@gmail.com>
Date: Mon, 25 Sep 2017 16:31:21 -0700
Subject: [PATCH] remove logic to append naming tags


---
 provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java | 3 ---
 1 file changed, 3 deletions(-)

diff --git a/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java b/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java
index e184ecb..4072c31 100644
--- a/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java
+++ b/provider/src/main/java/com/cloudera/director/aws/AbstractAWSTagHelper.java
@@ -117,9 +117,6 @@ public abstract class AbstractAWSTagHelper<T> {
   public List<T> getInstanceTags(InstanceTemplate template, String virtualInstanceId,
       List<T> userDefinedTags) {
     List<T> tags = Lists.newArrayList(
-        createTag(
-            Tags.ResourceTags.RESOURCE_NAME.getTagKey(),
-            String.format("%s-%s", template.getInstanceNamePrefix(), virtualInstanceId)),
         createClouderaDirectorIdTag(virtualInstanceId),
         createClouderaDirectorTemplateNameTag(template.getName())
     );
--
libgit2 0.26.0
```

**Comment by handavid** [comment]
@vinceprignano I had tried to send you a private message a while ago but had not received a response. I tried changing the Name through the customTagMappings and it worked for me. We'd need some more information about your setup and some log files to figure out why it's not working for you.

**Comment by vinceprignano** [comment]
Upgraded to 2.6 and it seems to work fine now :)
