### ISSUE TITLE
EBS io1 volumes support

### ISSUE THREAD

**Issue by vinceprignano** [cloudera/director-aws-plugin#5]
It looks like the AWS plugin doesn't support `io1` EBS volumes, is there any particular reason for it? I can open a PR if necessary.

**Comment by jadair-cloudera** [comment]
It's coming in a future Director release. In addition to the logic to request the volumes, this requires a new configuration parameter and extra validation logic.

**Comment by vinceprignano** [comment]
Perfect, thanks!
