### ISSUE TITLE
Incorrect project tagging?

### ISSUE THREAD

**Issue by sdavids13** [cloudera/director-aws-plugin#6]
I am attempting to enable ebs optimization on ec2 instances via the `ebsOptimized` property via version `2.4.1` but it doesn't seem to work. According to the code [here](https://github.com/cloudera/director-aws-plugin/blob/cloudera-director-2.4.1/provider/src/main/java/com/cloudera/director/aws/ec2/EC2InstanceTemplate.java#L112) it looks like it should be available though I did notice that both `cloudera-director-2.5.0` and `cloudera-director-2.4.1` point to the exact same commit tag which I found to be surprising. I would like to know if the tags that are associated with this repository is actually accurate? Should I be able to enable the ebs optimized ec2 instances for `v2.4.1`?

**Comment by handavid** [comment]
This does look incorrect to me. I will investigate and get a "cloudera-director-2.4.1-fixed" tag pushed up. There were no changes to the AWS plugin between Cloudera Director releases 2.4.0 and 2.4.1.

The ebsOptimized property should be available from Cloudera Director 2.5.x onwards.

Also, do note that this property has no effect on instance types that are EBSOptimized by default.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html

**Comment by handavid** [comment]
done
