### ISSUE TITLE
Support for AWS c5 instances

### ISSUE THREAD

**Issue by vinceprignano** [cloudera/director-aws-plugin#7]
https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/

**Comment by handavid** [comment]
@vinceprignano Thanks! We'll create an internal JIRA to add this to the next release. In the meantime, you can add c5 instances to your mapping files. 

https://www.cloudera.com/documentation/director/latest/topics/director_aws_new_instance_types.html#xd_583c10bfdbd326ba-590cb1d1-149e9ca9886--6f9f

**Comment by vinceprignano** [comment]
Thanks!
